In [6]:
import pickle
import numpy as np

In [7]:

ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [8]:
# Assume user input
# Pclass/gender/age/Sibsp/Parch/Fare/Embarked
test_input = np.array([2,'male',31.0,0,9,10.5,'S'],dtype=object).reshape(1,7)

In [9]:
test_input

array([[2, 'male', 31.0, 0, 9, 10.5, 'S']], dtype=object)

In [16]:
import pandas as pd

# Convert the NumPy array to a DataFrame with the appropriate column name
test_input_sex_df = pd.DataFrame(test_input[:, 1].reshape(1, 1), columns=['Sex'])

# Apply the transformation
test_input_sex = ohe_sex.transform(test_input_sex_df)


In [18]:
test_input_sex

array([[0., 1.]])

In [20]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [22]:
test_input_embarked

array([[0., 0., 1.]])

In [24]:
test_input_age = test_input[:,2].reshape(1,1)

In [30]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [34]:
test_input_transformed

array([[2, 0, 9, 10.5, 31.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [40]:
clf.predict(test_input_transformed)

array([0], dtype=int64)